# Generated by Django 3.0.8 on 2020-07-07 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_auto_20200705_1410'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookinstance',
            name='status',
            field=models.CharField(blank=True, choices=[('m', 'На обслуживании'), ('o', 'Выдана'), ('a', 'Доступна'), ('r', 'Зарезервирована')], default='m', help_text='Доступность книги', max_length=1),
        ),
    ]
